#!/bin/sh
set -e

if [ "$1" = "configure" ]; then

    DOCSET_PATH="/usr/share/labzeal/docsets/Python_3.docset"
    
    
    if [ -d "$DOCSET_PATH" ]; then
        # Besitz auf Root setzen
        chown -R root:root "$DOCSET_PATH"
        
        
        chmod -R a+rX "$DOCSET_PATH"
    fi
fi

exit 0
